# Lesson 32's clock, unchanged: the LCD in row a from column 9 with its
# contrast knob before it, and the clock module above the Mega. The snooze
# button goes in first, at the Mega's end; the passive buzzer and its 220 Ω
# resistor go after the LCD's pins; and the knob sits above the board,
# taking its power from the top rails.
bench = Bench ("Lesson 32's clock and LCD, with a knob on pins 18, 19 and 22, a snooze button on "
               "pin 23 and a passive buzzer on pin 10", columns=(1, 40))

bench.wire ("23", "j1")
bench.button (1)
bench.wire ("j3", "T-4")
bench.wire ("5V", "T+3")
bench.wire ("GND", "T-3")
bench.potentiometer ("e5", "e6", "e7")
bench.lcd (9, row="a", text=("Time    06:58:30", "Alarm   07:00   "))
bench.wire ("d5", "d9")
bench.wire ("c6", "c11")
bench.wire ("b7", "b10")
bench.wire ("e9", "T-9")
bench.wire ("e10", "T+10")
bench.wire ("e13", "T-13")
bench.wire ("31", "e12")
bench.wire ("32", "e14")
bench.wire ("33", "e19")
bench.wire ("34", "e20")
bench.wire ("35", "e21")
bench.wire ("36", "e22")
bench.resistor ("220 Ω", "e23", "f23")
bench.wire ("j23", "T+23")
bench.wire ("e24", "T-24")
bench.wire ("10", "j28")
bench.resistor ("220 Ω", "i28", "i32")
bench.buzzer ("g32", "g35", kind="passive")
bench.wire ("j35", "T-35")
bench.module ("rtc", at=(3.15, -1.25))
bench.wire ("GND", "rtc.GND")
bench.wire ("5V", "rtc.VCC")
bench.wire ("20", "rtc.SDA", color="green")
bench.wire ("21", "rtc.SCL", color="blue")
bench.module ("encoder", at=(7.9, -1.45))
bench.wire ("18", "encoder.CLK", color="white")
bench.wire ("19", "encoder.DT", color="brown")
bench.wire ("22", "encoder.SW", color="grey")
bench.wire ("T+30", "encoder.+")
bench.wire ("T-31", "encoder.GND")
